artefactual-labs/am-packbuild

- rpm/Makefile
- rpm/archivematica/package.spec
- rpm/fits/Dockerfile
- rpm/fits/Makefile
- rpm/fits/files/fits-home.patch
- rpm/fits/files/fits-nailgun.service
- rpm/fits/package.spec
- rpm/nailgun/Dockerfile
- rpm/nailgun/Makefile
- rpm/nailgun/package.spec
> rpm: add fits

- rpm/Makefile
- rpm/archivematica/package.spec
- rpm/atool/Dockerfile
- rpm/atool/Makefile
- rpm/atool/files/atool.keyring
- rpm/atool/package.spec
Added atool rpm using the specfile from suse avaliable [here](https://build.opensuse.org/package/view_file/Archiving/atool/atool.spec)
> rpm: add atool v0.39.0

- rpm/Makefile
- rpm/archivematica/package.spec
- rpm/jhove/Dockerfile
- rpm/jhove/Makefile
- rpm/jhove/files/paths.patch
- rpm/jhove/package.spec
> rpm: add jhove 1.12.32

- rpm/fits/files/fits-log4j.patch
> rpm: add log4j config to fits

- rpm-testing/Vagrantfile
* Added alias for 7zip
* Enabled fits-nailgun service
> rpm: update Vagrantfile

- packer/templates/vagrant-box-16.04-atom/provisioning/host_vars/all
- packer/templates/vagrant-box-16.04-atom/provisioning/singlenode.yml
- packer/templates/vagrant-box-16.04-atom/requirements.yml
- packer/templates/vagrant-box-16.04-atom/template.json
- packer/templates/vagrant-box-atom/provisioning/host_vars/all
- packer/templates/vagrant-box-atom/provisioning/singlenode.yml
- packer/templates/vagrant-box-atom/requirements.yml
- packer/templates/vagrant-box-atom/template.json
- Change AtoM branch
- Use elastic.elasticsearch role to install ES 5.x
- Set memory and cpus for vboxes in packer templates
> AtoM 2.5 changes

- debs/trusty/archivematica-storage-service/debian-storage-service/control
- debs/xenial/archivematica-storage-service/debian-storage-service/control
- rpm/archivematica-storage-service/package.spec
This closes https://github.com/artefactual-labs/am-packbuild/issues/74.
> ss: add gnupg and rng-tools dependencies

- rpm/archivematica-storage-service/package.spec
> rpm/ss: add p7zip dependency

- debs/siegfried/Makefile
- rpm/siegfried/Makefile
> pkgs: update siegfried to 1.7.6

- debs/trusty/archivematica-storage-service/debian-storage-service/archivematica-storage-service.install
- debs/xenial/archivematica-storage-service/debian-storage-service/archivematica-storage-service.install
> deb ss: rename storageService conf file

- debs/trusty/archivematica-storage-service/Dockerfile
- debs/xenial/archivematica-storage-service/Dockerfile
- debs/xenial/archivematica-storage-service/debian-storage-service/control
- debs/xenial/archivematica-storage-service/debian-storage-service/patches/remove-psycopg-requirement.diff
- debs/xenial/archivematica-storage-service/debian-storage-service/patches/series
- debs/xenial/archivematica-storage-service/debian-storage-service/rules
Also, look in pip index for unmeet dependencies ( workaround for #84 )
> Remove psycopg dependency in xenial

- debs/trusty/archivematica-storage-service/debian-storage-service/control
- debs/trusty/archivematica/debian-MCPClient/control
- debs/xenial/archivematica-storage-service/debian-storage-service/control
- debs/xenial/archivematica/debian-MCPClient/control
- rpm/archivematica/archivematica.spec
Mediaconch for ubuntu, it has been added to ubuntu-externas repo.
Centos carries an up-to-date version (17.08)
> Add dependencies to deb packages

- debs/trusty/archivematica/Dockerfile
Else, cryptography fails to build. Closes #94
> am trusty: update setuptools and virtualenv

- debs/xenial/jhove/Makefile
- debs/xenial/jhove/package/DEBIAN/control
* Create .empty file, so usr/share/java/ is under git
* Update Makefile and control to support RELEASE parameter
> jhove: update packaging scripts

- rpm/archivematica/archivematica.spec
> am rpm: delete python-unidecode

- rpm/archivematica-storage-service/etc/archivematica-storage-service.nginx
- rpm/archivematica/etc/dashboard.nginx
Closes artefactual-labs/am-packbuild#106
> Forward request only to ipv4 address

- debs/xenial/archivematica/debian-MCPServer/archivematica-mcp-server.service
- rpm/archivematica/etc/archivematica-mcp-server.service
Closes artefactual/archivematica#953
> Don't start mcp-s until mysql is running

- debs/xenial/hashdeep/Dockerfile
- debs/xenial/hashdeep/Makefile
- rpm/archivematica/Makefile
> Backport hashdeep package from Ubuntu 17.10

- rpm/archivematica-storage-service/package.spec
- rpm/archivematica/archivematica.spec
Also, improve user handling.
This fixes artefactual-labs/am-packbuild#116 and
artefactual/archivematica#955
> Create archivematica user group in rpms

- README.md
- rpm-testing/README.md
This relates to #124 and it's work in progress.
> README: add usage notes

- rpm/archivematica-storage-service/Makefile
- rpm/archivematica-storage-service/package.spec
- rpm/archivematica/Makefile
- rpm/archivematica/archivematica.spec
> rpm: honour BRANCH environment var

- debs/trusty/archivematica-storage-service/debian-storage-service/archivematica-storage-service.install
- debs/trusty/archivematica-storage-service/debian-storage-service/patches/storage-service-init.diff
- debs/trusty/archivematica-storage-service/debian-storage-service/postinst
- debs/trusty/archivematica-storage-service/debian-storage-service/postrm
- debs/trusty/archivematica/debian-MCPClient/archivematica-mcp-client.default
- debs/trusty/archivematica/debian-MCPClient/patches/mcp-client-init.diff
- debs/trusty/archivematica/debian-MCPServer/patches/mcp-server-init.diff
- debs/trusty/archivematica/debian-dashboard/patches/dashboard-init.diff
This relates to #119.
Similar PRs: #122 and #130.
For local testing, #127 could help although it only targets Xenial for now but easy to tweak.
> debs/trusty: change venv install root

- rpm/archivematica-storage-service/etc/archivematica-storage-service.nginx
- rpm/archivematica/etc/dashboard.nginx
Use same values than in Ubuntu:
- Set proxy_read_timeout to 172800s
- Set client_max_body_size to 256M
- Remove keepalive_timeout
- SS: remove error blocks
> rpm: update nginx config

- debs/trusty/archivematica/debian-dashboard/control
- debs/xenial/archivematica/debian-dashboard/control
> Add git dependency to archivematica deb packages

- debs/trusty/archivematica/debian-MCPClient/rules
- debs/trusty/archivematica/debian-MCPServer/rules
- debs/trusty/archivematica/debian-archivematicaCommon/rules
- debs/trusty/archivematica/debian-dashboard/rules
Also, removed some spaces from the debian/rules file
This closes #149
> Add DH_VIRTUALENV_INSTALL_ROOT to trusty am packages

- debs/xenial/archivematica/Dockerfile
It includes dh-virtualenv 1.0-1, that fixes artefactual/archivematica#1042
> deb xenial: add ubuntu-externals package

- debs/trusty/archivematica-storage-service/debian-storage-service/rules
- debs/trusty/archivematica/debian-MCPClient/rules
- debs/trusty/archivematica/debian-MCPServer/rules
- debs/trusty/archivematica/debian-dashboard/rules
This closes https://github.com/artefactual/archivematica/issues/1064.
> Fix pip version issue in deb trusty
